src/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Auth
 */
Route::get('/register', 'Auth\RegisterController@registerForm')->name('registerForm');
Route::post('/register', 'Auth\RegisterController@register')->name('register');
Route::get('/login', 'Auth\LoginController@loginForm')->name('loginForm');
Route::post('/login', 'Auth\LoginController@login')->name('login');
Route::get('/logout', 'Auth\LogoutController@logout')->name('logout');
Route::get('/activate/{key}', 'Auth\ActivateController@activateEmail')->name('activateEmail');
Route::get('/recovery', 'Auth\RecoveryController@recoveryForm')->name('recoveryForm');
Route::post('/recovery', 'Auth\RecoveryController@recovery')->name('recovery');
Route::get('/reset/{key}', 'Auth\ResetPasswordController@resetForm')->name('resetForm');
Route::post('/reset/{key}', 'Auth\ResetPasswordController@reset')->name('reset');


Route::get('/sitemap.xml', 'SitemapController@xml')->name('sitemap.xml');
Route::get('/', 'HomeController@index')->name('home');
Route::get('/term', 'TermController@index')->name('term');


/**
 * Admin
 */
Route::namespace('Admin')->prefix('voito')->name('admin.')->middleware('admin')->group(function () {
    Route::get('/', 'IndexController@dashboard')->name('home');
    Route::get('/clear-cache', 'IndexController@clearCache')->name('clearCache');

    Route::prefix('/place')->name('place.')->group(function () {

        Route::get('/', 'PlaceController@listAll')->name('listAll');
        Route::post('/', 'PlaceController@create')->name('create');
        Route::get('/create', 'PlaceController@createForm')->name('createForm');
        Route::get('/{id}', 'PlaceController@show')->name('show');
        Route::put('/{id}', 'PlaceController@update')->name('update');
        Route::get('/{id}/edit', 'PlaceController@updateForm')->name('updateForm');
        Route::get('/{id}/destroy', 'PlaceController@destroy')->name('destroy');

        Route::get('/{id}/move', 'PlaceController@moveForm')->name('moveForm');
        Route::post('/{id}/move', 'PlaceController@move')->name('move');
        Route::get('/{id}/make-root', 'PlaceController@makeRoot')->name('make-root');
        Route::get('/{id}/set-active', 'PlaceController@setActive')->name('active');
        Route::get('/{id}/set-un-active', 'PlaceController@setUnActive')->name('un-active');
        Route::get('/{id}/up/{step?}', 'PlaceController@shiftUp')->name('up');
        Route::get('/{id}/down/{step?}', 'PlaceController@shiftDown')->name('down');
    });

    Route::prefix('/ad-category')->name('ad-category.')->group(function () {

        Route::get('/', 'AdCategoryController@listAll')->name('listAll');
        Route::post('/', 'AdCategoryController@create')->name('create');
        Route::get('/create', 'AdCategoryController@createForm')->name('createForm');
        Route::get('/{id}', 'AdCategoryController@show')->name('show');
        Route::put('/{id}', 'AdCategoryController@update')->name('update');
        Route::get('/{id}/edit', 'AdCategoryController@updateForm')->name('updateForm');
        Route::get('/{id}/destroy', 'AdCategoryController@destroy')->name('destroy');

        Route::get('/{id}/move', 'AdCategoryController@moveForm')->name('moveForm');
        Route::post('/{id}/move', 'AdCategoryController@move')->name('move');
        Route::get('/{id}/make-root', 'AdCategoryController@makeRoot')->name('make-root');
        Route::get('/{id}/set-active', 'AdCategoryController@setActive')->name('active');
        Route::get('/{id}/set-un-active', 'AdCategoryController@setUnActive')->name('un-active');
        Route::get('/{id}/up/{step?}', 'AdCategoryController@shiftUp')->name('up');
        Route::get('/{id}/down/{step?}', 'AdCategoryController@shiftDown')->name('down');
    });

    Route::prefix('/job-industry')->name('job-industry.')->group(function () {

        Route::get('/', 'JobIndustryController@listAll')->name('listAll');
        Route::post('/', 'JobIndustryController@create')->name('create');
        Route::get('/create', 'JobIndustryController@createForm')->name('createForm');
        Route::get('/{id}', 'JobIndustryController@show')->name('show');
        Route::put('/{id}', 'JobIndustryController@update')->name('update');
        Route::get('/{id}/edit', 'JobIndustryController@updateForm')->name('updateForm');
        Route::get('/{id}/destroy', 'JobIndustryController@destroy')->name('destroy');

        Route::get('/{id}/move', 'JobIndustryController@moveForm')->name('moveForm');
        Route::post('/{id}/move', 'JobIndustryController@move')->name('move');
        Route::get('/{id}/make-root', 'JobIndustryController@makeRoot')->name('make-root');
        Route::get('/{id}/up/{step?}', 'JobIndustryController@shiftUp')->name('up');
        Route::get('/{id}/down/{step?}', 'JobIndustryController@shiftDown')->name('down');
    });

    Route::prefix('/job-professional-area')->name('job-professional-area.')->group(function () {

        Route::get('/', 'JobProfessionalAreaController@listAll')->name('listAll');
        Route::post('/', 'JobProfessionalAreaController@create')->name('create');
        Route::get('/create', 'JobProfessionalAreaController@createForm')->name('createForm');
        Route::get('/{id}', 'JobProfessionalAreaController@show')->name('show');
        Route::put('/{id}', 'JobProfessionalAreaController@update')->name('update');
        Route::get('/{id}/edit', 'JobProfessionalAreaController@updateForm')->name('updateForm');
        Route::get('/{id}/destroy', 'JobProfessionalAreaController@destroy')->name('destroy');

        Route::get('/{id}/move', 'JobProfessionalAreaController@moveForm')->name('moveForm');
        Route::post('/{id}/move', 'JobProfessionalAreaController@move')->name('move');
        Route::get('/{id}/make-root', 'JobProfessionalAreaController@makeRoot')->name('make-root');
        Route::get('/{id}/up/{step?}', 'JobProfessionalAreaController@shiftUp')->name('up');
        Route::get('/{id}/down/{step?}', 'JobProfessionalAreaController@shiftDown')->name('down');
    });

    Route::prefix('/user')->name('user.')->group(function () {

        Route::get('/active', 'UserController@listActive')->name('listActive');
        Route::get('/all', 'UserController@listAll')->name('listAll');
        Route::get('/banned', 'UserController@listBanned')->name('listBanned');
        Route::get('/deleted', 'UserController@listDeleted')->name('listDeleted');

        Route::get('/create', 'UserController@createForm')->name('createForm');
        Route::post('/', 'UserController@create')->name('create');

        Route::get('/{id}', 'UserController@show')->name('show');

        Route::get('/{id}/edit', 'UserController@updateForm')->name('updateForm');
        Route::put('/{id}', 'UserController@update')->name('update');

        Route::get('/{id}/password', 'UserController@passwordForm')->name('passwordForm');
        Route::put('/{id}/password', 'UserController@password')->name('password');

        Route::get('/{id}/delete', 'UserController@delete')->name('delete');
        Route::get('/{id}/un-delete', 'UserController@unDelete')->name('unDelete');
        Route::get('/{id}/destroy', 'UserController@destroy')->name('destroy');
        Route::get('/{id}/ban', 'UserController@ban')->name('ban');
        Route::get('/{id}/un-ban', 'UserController@unBan')->name('unBan');
    });

    Route::prefix('/contacts')->name('contact.')->group(function () {
        Route::get('/active', 'ContactController@listActive')->name('listActive');
        Route::get('/all', 'ContactController@listAll')->name('listAll');
        Route::get('/unActivated', 'ContactController@listUnActivated')->name('listUnActivated');
        Route::get('/banned', 'ContactController@listBanned')->name('listBanned');
        Route::get('/deleted', 'ContactController@listDeleted')->name('listDeleted');
        Route::get('/user/{id}', 'ContactController@listByUser')->name('listByUser');
        Route::post('/user/{id}', 'ContactController@create')->name('create');
        Route::get('/user/{id}/create', 'ContactController@createForm')->name('createForm');
        Route::get('/{id}', 'ContactController@show')->name('show');
        Route::put('/{id}', 'ContactController@update')->name('update');
        Route::get('/{id}/update', 'ContactController@updateForm')->name('updateForm');

        Route::get('/{id}/delete', 'ContactController@delete')->name('delete');
        Route::get('/{id}/un-delete', 'ContactController@unDelete')->name('unDelete');
        Route::get('/{id}/destroy', 'ContactController@destroy')->name('destroy');
        Route::get('/{id}/ban', 'ContactController@ban')->name('ban');
        Route::get('/{id}/un-ban', 'ContactController@unBan')->name('unBan');
        Route::get('/{id}/activate', 'ContactController@activate')->name('activate');
        Route::get('/{id}/un-activate', 'ContactController@deactivate')->name('deactivate');
    });

    Route::prefix('/tokens')->name('token.')->group(function () {
        Route::get('/', 'TokenController@listAll')->name('listAll');
        Route::get('/user/{id}', 'TokenController@listByUser')->name('listByUser');
        Route::get('/contact/{id}', 'TokenController@listByContact')->name('listByContact');
        Route::get('/destroy/{type}/{value}', 'TokenController@destroy')->name('destroy');
    });

    Route::prefix('/ads')->name('ad.')->group(function () {
        Route::get('/index', 'AdController@listAll')->name('listAll');

        Route::get('/create', 'AdController@createForm')->name('createForm');

src/app/Http/Controllers/Ad/CreateController.php
<?php

namespace App\Http\Controllers\Ad;

use App\Http\Controllers\Controller;
use App\Http\Requests\AdStore;
use App\Models\Ad;
use App\Models\AdCategory;
use App\Models\Place;
use Exception;
use Illuminate\Http\RedirectResponse;

class CreateController extends Controller
{

    public function showForm(string $category = null)
    {

        if ($category == 'resume') {
            return view('ad.create.resumes');
        } elseif ($category == 'vacancy') {
            return view('ad.create.vacancies');
        } elseif ($category == null) {
            return view('ad.create.index');
        } else {
            abort(404);
        }
    }

    public function showResumeForm()
    {

        return view('ad.create-resume');
    }

    public function showVacancyForm()
    {

        return view('ad.create-vacancy');
    }

    /**
     * @param AdStore $request
     * @return RedirectResponse
     * @throws Exception
     */
    public function create(AdStore $request)
    {
        $model = new Ad();
        $model->initialSave($request);
        return redirect()->route('ad.view.full', ['id' => $model->ad_id, 'category' => $model->category->code]);
    }

    /**
     * @param string $category
     * @return AdCategory
     */
    protected function checkCategory(string $category): AdCategory
    {
        return AdCategory::whereCode($category)->firstOrFail();
    }

}

src/app/Http/Controllers/Ad/ManageController.php
<?php

namespace App\Http\Controllers\Ad;

use App\Http\Controllers\Controller;
use App\Models\Ad;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\RedirectResponse;

class ManageController extends Controller
{

    /**
     * @param $id
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function delete(int $id)
    {
        $model = $this->findAd($id);
        $this->authorize('update', $model);
        $model->markDeleted();
        return back();
    }

    /**
     * @param int $id
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function unDelete(int $id)
    {
        $model = $this->findAd($id);
        $this->authorize('update', $model);
        $model->markUnDeleted();
        return back();
    }

    /**
     * @param $id
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function block(int $id)
    {
        $model = $this->findAd($id);
        $this->authorize('admin', $model);
        $model->ban();
        return back();
    }

    /**
     * @param int $id
     * @return RedirectResponse
     * @throws AuthorizationException
     */
    public function unblock(int $id) {
        $model = $this->findAd($id);
        $this->authorize('admin', $model);
        $model->unBan();
        return back();
    }

    /**
     * @param int $id
     * @return Ad|Ad[]|Collection|Model
     */
    protected function findAd(int $id)
    {
        return Ad::findOrFail($id);
    }

}

src/app/Http/Controllers/Ad/UpdateController.php
<?php

namespace App\Http\Controllers\Ad;

use App\Http\Controllers\Controller;
use App\Http\Requests\AdStore;
use App\Models\Ad;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Contracts\View\Factory;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;
use Illuminate\View\View;

class UpdateController extends Controller {

    /**
     * @param int $id
     * @return Factory|View
     * @throws AuthorizationException
     */
    public function updateForm(int $id)
    {
        $model = $this->findAd($id);
        $this->authorize('update', $model);

        return view("ad.update.{$model->category->code}");
    }

    public function update(AdStore $request, $id) {

    }


    /**
     * @param int $id
     * @return Ad|Ad[]|Collection|Model
     */
    protected function findAd(int $id)
    {
        return Ad::findOrFail($id);
    }
}

src/app/Http/Controllers/Ad/ViewController.php
<?php

namespace App\Http\Controllers\Ad;

use App\Http\Controllers\Controller;
use App\Models\Ad;
use App\Models\AdCategory;
use App\Models\Place;

class ViewController extends Controller
{

    public function show(string $place, string $category, int $id)
    {

        $model = Ad::with(['photos', 'user'])
            ->leftJoin('places', 'ads.place_id', '=', 'places.place_id')
            ->leftJoin('ad_categories', 'ads.ad_category_id', '=', 'ad_categories.ad_category_id')
            ->where([
                'places.code' => $place,
                'ad_categories.code' => $category
            ])
            ->findOrFail($id);

        session(['place' => $place]);

        $model->increment('views');

        return view("ad.view.{$category}", ['model' => $model]);
        /*if ($model->category->code == 'vacancies') {
            return view('ad.view.vacancy', ['model' => $model->adVacancy]);
        } elseif ($model->category->code == 'resumes') {
            return view('ad.view.resume', ['model' => $model->adResume]);
        }*/
    }

    /**
     * @param string $place
     * @return Place
     */
    protected function checkPlace(string $place): Place
    {
        return Place::whereCode($place)->firstOrFail();
    }

    /**
     * @param string $category
     * @return AdCategory
     */
    protected function checkCategory(string $category): AdCategory
    {
        return AdCategory::whereCode($category)->firstOrFail();
    }

}

src/resources/views/admin/ad/_blockedButton.blade.php
@php
    /** @var \App\Models\Ad $ad */
@endphp
@if( $ad->isBanned )
    {{ $ad->blocked_at }}
    <br>
    <a class="label label-success"
       href="{{ route('admin.ad.unBan', ['id' => $ad->ad_id]) }}">{{ __('admin.grid-btn.unBan') }}</a>
@else
    <a class="label label-danger"
       href="{{ route('admin.ad.ban', ['id' => $ad->ad_id]) }}">{{ __('admin.grid-btn.ban') }}</a>
@endif

src/resources/views/admin/ad/_buttons.blade.php
@php
    /** @var \App\Models\Ad $ad */
@endphp
<a href="{{route('admin.ad.updateForm', ['id' => $ad->ad_id])}}"
   title="{{ __('admin.update') }}"><i class="fa fa-fw fa-edit"></i></a>
<a href="{{route('admin.ad.destroy', ['id' => $ad->ad_id])}}"
   title="{{ __('admin.grid-btn.delete') }}"><i class="fa fa-fw fa-trash"></i></a>
<a href="{{ route('admin.ad.show', ['id' => $ad->ad_id]) }}"
   title="{{ __('admin.grid-btn.show') }}"><i class="fa fa-fw fa-eye"></i></a>

src/resources/views/admin/ad/_deletedButton.blade.php
@php
    /** @var \App\Models\Ad $ad */
@endphp
@if( $ad->isDeleted )
    {{ $ad->deleted_at }}
    <br>
    <a class="label label-success"
       href="{{ route('admin.ad.unDelete', ['id' => $ad->ad_id]) }}">{{ __('admin.grid-btn.unDelete') }}</a>
@else
    <a class="label label-danger"
       href="{{ route('admin.ad.delete', ['id' => $ad->ad_id]) }}">{{ __('admin.grid-btn.delete') }}</a>
@endif

src/resources/views/admin/ad/_form.blade.php
<?php

src/resources/views/admin/ad/_menu.blade.php
@php
    /** @var string $status */
    $status = request()->get('status');
@endphp
<ul class="nav nav-pills margin-bottom">
    <li {{ $status == null ?  'class=active' : '' }}>
        <a href="{{ request()->fullUrlWithQuery(['status' => null]) }}">{{__('admin.menu.listActive')}}</a>
    </li>
    <li {{ $status == 'banned' ?  'class=active' : '' }}>
        <a href="{{ request()->fullUrlWithQuery(['status' => 'banned']) }}">{{__('admin.menu.listBanned')}}</a>
    </li>
    <li {{ $status == 'deleted' ?  'class=active' : '' }}>
        <a href="{{ request()->fullUrlWithQuery(['status' => 'deleted']) }}">{{__('admin.menu.listDeleted')}}</a>
    </li>
    <li {{ $status == 'all' ?  'class=active' : '' }}>
        <a href="{{ request()->fullUrlWithQuery(['status' => 'all']) }}">{{__('admin.menu.listAll')}}</a>
    </li>
    <li>
        <a href="{{ route('admin.ad.listAll') }}">{{__('admin.menu.clear-filters')}}</a>
    </li>
    <li>
        <a href="{{ route('admin.ad.createForm') }}">{{ __('ad.admin.createForm') }}</a>
    </li>
</ul>

src/resources/views/admin/ad/_refreshButton.blade.php
@php
    /** @var \App\Models\Ad $ad */
@endphp
{{ $ad->refreshed_at }}
<br>
<a class="label label-success"
   href="{{ route('admin.ad.refresh', ['id' => $ad->ad_id]) }}">{{ __('admin.grid-btn.refresh') }}</a>

src/resources/views/admin/ad/createForm.blade.php
@php
    $title = __('ad.admin.createForm');
@endphp

@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <h1>{{ $title }}</h1>
@stop

@section('content')
    @include('admin.ad._menu')

    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">{{ $title }}</h3>
            </div>
            <div class="box-body">
                <ad-form></ad-form>
                <li><a href="{{ route('admin.ad.createFormVacancy') }}">{{ __('ad.admin.createFormVacancy') }}</a></li>
                <li><a href="{{ route('admin.ad.createFormResume') }}">{{ __('ad.admin.createFormResume') }}</a></li>
            </div>
        </div>
    </div>
@stop

src/resources/views/admin/ad/createFormVacancy.blade.php
@php
    $title = __('contact.admin.createFormVacancy');
@endphp

@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <h1>{{ $title }}</h1>
@stop

@section('content')
    @include('admin.contact._menu')

    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">{{ $title }}</h3>
            </div>
            <form action="{{route('admin.ad.create')}}" method="post">
                <div class="box-body">
                    @csrf

                    @include('admin.contact._form', ['category' => 'vacancy'])

                </div>
                <div class="box-footer">
                    <button class="btn btn-primary">{{ __('admin.create') }}</button>
                </div>
            </form>
        </div>
    </div>
@stop

src/resources/views/admin/ad/listAll.blade.php
@php
    /** @var string $title */
    $title = __('ad.admin.list');
@endphp

@extends('adminlte::page')

@section('title', $title)

@section('content_header')
    <h1>{{ $title }}</h1>
@stop

@section('content')
    @include('admin.ad._menu')

    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3>{{ $title }}</h3>
            </div>
            <div class="box-body table-responsive no-padding">
                <div class="col-sm-12">
                    <table class="table table-bordered table-hover dataTable table-align-middle" role="grid"
                           id="ad-table">
                        <thead>
                        <tr role="row">
                            <th>{{ __('ad.field.ad_id') }}</th>
                            <th>{{ __('ad.field.user_id') }}</th>
                            <th>{{ __('ad.field.phone') }}</th>
                            <th>{{ __('ad.field.view_contact') }}</th>
                            <th>{{ __('ad.field.category') }}</th>
                            <th>{{ __('ad.field.place') }}</th>
                            <th>{{ __('ad.field.created_at') }}</th>
                            <th>{{ __('ad.field.refreshed_at') }}</th>
                            <th>{{ __('ad.field.blocked_at') }}</th>
                            <th>{{ __('ad.field.deleted_at') }}</th>
                            <th>{{ __('admin.grid-btn.buttons') }}</th>
                        </tr>
                        </thead>
                    </table>

                </div>
            </div>
            <div class="box-footer">
            </div>
        </div>
    </div>
@stop
@section('adminlte_js')
    @parent

    <script type="text/javascript">
        $(document).ready(function () {
            $('#ad-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "",
                columns: [
                    {data: 'ad_id', name: 'ads.ad_id'},
                    {data: 'user_id', name: 'ads.user_id'},
                    {data: 'phone', name: 'ads.phone', orderable: false},
                    {data: 'view_contact', name: 'ads.view_contact', searchable: false},
                    {data: 'ad_category_id', name: 'ads.ad_category_id', searchable: false},
                    {data: 'place', name: 'place.name', searchable: false},
                    {data: 'created_at', name: 'ads.created_at', searchable: false},
                    {data: 'refreshed_at', name: 'ads.refreshed_at', searchable: false},
                    {data: 'blocked_at', name: 'ads.blocked_at', searchable: false},
                    {data: 'deleted_at', name: 'ads.deleted_at', searchable: false},
                    {data: 'buttons', 'name': 'buttons', orderable: false, searchable: false}
                ],
                order: [[0, 'desc']],
                language: {
                    "url": "//cdn.datatables.net/plug-ins/1.10.7/i18n/Russian.json"
                },
                lengthMenu: [[50, 100, 500, -1], [50, 100, 500, "All"]]
            });
        });
    </script>
@stop